Entities/Kategori.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EticaretProjesi.Entities
{
    public class Kategori
    {
        public int Id { get; set; }
        [MaxLength(100)]
        public string Ad { get; set; }

        public List<UrunKategori>  UrunKategoriler { get; set; }
        //1 kategorinin 1 den fazla ürünü olabilir
    }
}

Areas/Admin/Controllers/KategoriController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EticaretProjesi.Entities;
using EticaretProjesi.Interfaces;
using EticaretProjesi.Models;

namespace EticaretProjesi.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class KategoriController : Controller
    {
        
        private readonly IKategoryRepository _kategoryRepository;

        public KategoriController(IKategoryRepository kategoryRepository)
        {
            _kategoryRepository = kategoryRepository;
        }

        public IActionResult Index()
        {
            return View(_kategoryRepository.GetirHepsi());
        }

        public IActionResult Ekle()
        {
            return View(new KategoriEkleModel());
        }

        [HttpPost]
        public IActionResult Ekle(KategoriEkleModel model)
        {
            if (ModelState.IsValid)
            {
                _kategoryRepository.Ekle(new Kategori
                {
                    Ad = model.Ad
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Guncelle(int id)
        {
            var guncellenecekKategori = _kategoryRepository.GetirIdile(id);
            KategoriGuncelleModel model = new KategoriGuncelleModel
            {
                Id=guncellenecekKategori.Id,
                Ad = guncellenecekKategori.Ad
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Guncelle(KategoriGuncelleModel model)
        {
            if (ModelState.IsValid)
            {
                var guncellenecekKategori = _kategoryRepository.GetirIdile(model.Id); //id alıcak 
                guncellenecekKategori.Ad = model.Ad;
                //modelden gelen ad
                _kategoryRepository.Guncelle(guncellenecekKategori);
                return RedirectToAction("Index");
            }
              
            return View(model);
        }

        public IActionResult Sil(int id)
        {
            _kategoryRepository.Sil(new Kategori{Id = id});
            return RedirectToAction("Index");
        }
    }
}

Areas/Admin/Views/Kategori/Ekle.cshtml
@model KategoriEkleModel

<form asp-action="Ekle" asp-controller="Kategori" asp-area="Admin" method="post"
class="w-75 mx-auto p-3" enctype="multipart/form-data">
<!--enctype="multipart/form-data" bu form aracılığıyla dosya tasımamızı sağlar yoksa null döner-->
<div class="form-group">
    <label>Kategorinin Adı:</label>
    <span asp-validation-for="Ad" class="text-danger"></span>
    <input asp-for="Ad" class="form-control" />
</div>
<div class="form-group">
    <a asp-action="Index" asp-controller="Kategori" asp-area="Admin" class="btn btn-warning">Vazgec</a>
    <button type="submit" class="btn btn-primary">Kaydet</button>
</div>
</form>

@section JavaScript
{

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

Areas/Admin/Views/Kategori/Guncelle.cshtml
@model KategoriGuncelleModel


<form asp-action="Guncelle" asp-controller="Kategori" asp-area="Admin" method="post"
      class="w-75 mx-auto p-3" enctype="multipart/form-data">
    <!--enctype="multipart/form-data" bu form aracılığıyla dosya tasımamızı sağlar yoksa null döner-->
    <input type="hidden" asp-for="@Model.Id"/>
    <div class="form-group">
        <label>Kategorinin Adı:</label>
        <span asp-validation-for="Ad" class="text-danger"></span>
        <input asp-for="Ad" class="form-control" />
    </div>
    <div class="form-group">
        <a asp-action="Index" asp-controller="Kategori" asp-area="Admin" class="btn btn-warning">Vazgec</a>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>
</form>

@section JavaScript
{

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
}

Areas/Admin/Views/Kategori/Index.cshtml
@model List<Kategori>

<a asp-action="Ekle" asp-controller="Kategori" asp-area="Admin" class="btn btn-primary btn-sm my-2">Ekle</a>

<table class="table table-sm table-bordered table-hover mt-2">
    <tr>
        <th>Id</th>
        <th>Ad</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Ad</td>
            <td>
                <a asp-action="Guncelle" asp-controller="Kategori"
                   asp-route-id="@item.Id" asp-area="Admin" class="btn btn-warning btn-sm">
                    Güncelle
                </a>
                <a asp-action="Sil" asp-controller="Kategori"
                   asp-route-id="@item.Id" asp-area="Admin" class="btn btn-danger btn-sm">
                    Sil
                </a>
            </td>
        </tr>
    }

</table>